### ISSUE TITLE
ClusterAllocator

### ISSUE THREAD

**Issue by problame** [KIT-MAMID/mamid#13]
- [x] hook up with replica_set API calls -> use tx there
- [x] side effects (bus messages)
- [x] must re-run after a migration to remove the old (disabled) members -> periodic trigger?
 - [x] also relevant for cleanup of deleted mongods, see #9, #17 
- [x] prefer reachable slaves when adding => ORDER, ...
  - needs communication error in slave #14 
- [x] prefer unreachable slaves when removing => ORDER
- [x] do not spawn twice on same slave
- [x] proper logging

**Comment by problame** [comment]
@antonxy `also relevant for cleanup of deleted mongods, see` is that fixed?

**Comment by antonxy** [comment]
Yes, is fixed, I implemented a periodic trigger

**Comment by problame** [comment]
Fixed as of `5d9d2791e32cfb5b6d7b959c40c79337c72cd143`
