### ISSUE TITLE
Slaves with Communication Error

### ISSUE THREAD

**Issue by problame** [KIT-MAMID/mamid#14]
The monitor may encounter a communication error when observing a slave.
The deployer may encounter a communication error when deploying mongods on a slave.

A communication error should be respected by the cluster allocator:
- do not provision to a slave with communication error

(changes already made by earlier cluster allocator runs should not be reversed. this case is handled by setting the affected slave to 'disabled' state in the GUI)

**Comment by antonxy** [comment]
Resolved as of 1681370342184f020aec4cd2ef6c5e2e428d92e5
