### ISSUE TITLE
Disabling Slaves with indisposable Mongods

### ISSUE THREAD

**Issue by problame** [KIT-MAMID/mamid#19]
Current Situation:

Given unsatisfiable constraints for a replica set, setting a Slave to `disabled`

* is permitted by `masterapi/slaves.go:changeToSlaveAllowed()`
* does not _directly_ change the DesiredState of Slave's Mongods
* triggers a ClusterAllocator run
  * removes unneeded Mongods, ones on disabled slaves first (set desiredstate = destroyed)
  * adds new Mongods where possible (question of satisfiability of replica set constraints)

## Case:
If a replica set's constraints are already not satisfiable/-ied, setting a slave hosting a member of the replica set to `disabled` **does** change the slave's ConfiguredState but **does not** change the running Mongod's DesiredState .

## Problem 1:
This not communicated via the GUI (because the GUI visualized the slave's configured state as disabled)
The GUI should display `configured_state=disabled & slave has still running mongods` differently than `configured_state=disabled & slave has no running mongods`

## Problem 2:
The ProblemManager displays a warning about the replica set being degraded (because we just disabled one slave) but the Mongod is still running.
I have not yet investigated why this is the case, but the ProblemManager should always report the current state in its error messages, i.e. the `replica_set_effective_members` view.

**Comment by janisstreib** [comment]
Problem 1 requires an API change (e.g. extend the attributes of the slave api object).

**Comment by problame** [comment]
Regarding the API change, I guess we should choose one of the following alternatives

1. return the amount of running Mongods per slave, e.g. `running_mongod_count`
2. return an array of Mongod objects
3. return a generic field `configured_state_transitioning` (bool) which is set to true whenever a slave is transitioning to the state described in `configured_state`

I guess option 2 is preferrable over option 1 because it's a little more reusable (and we might need to define a Mongod API object for the purpose of exporting the members of a replica set anyways).

Option1 and 2 however require the client to do the semantic check `configured_state=disabled & slave has still running mongods??`, which is debatable.

Option 3 is the most generic and additionally the slightest deviation from the spec.

Discuss! :)

however, I am unsure wh

**Comment by antonxy** [comment]
My suggestion would be introducing a mongod api object which can be queried by replica set and by slave.
If we want to the gui could then also display a list of mongds per slave and replica set (or just the count).

If we also include the hostname of the parent slave this would also solve querying the host:port tuples of replica sets ( #21 )

I think the gui does not have to do the semantic check, if you edit the slave you get an error. Its just nice for the user to see that mongods are still there.

In general its nice for the user to see which/how many mongods have been allocated on the slave.

**Comment by problame** [comment]
> I think the gui does not have to do the semantic check, if you edit the slave you get an error. Its just nice for the user to see that mongods are still there.

There's no error right now. It's implicit, in that `has_error = ... OR (configured_state = disabled & count(effective mongods on slave) > 0`

Remember we name the state clicked by the user `configured_state`, not `actual_state`, because disabling a slave in the GUI is merely an **indication** to the ClusterAllocator to migrate the Mongods away, which might take a long time.
(Please correct me if I'm wrong)

Hence, I vote for both

* implementing the API as you described (low prio for query-by-replica-set, as it's not a required feature) 
* adding the `configured_state_transitioning` (bool) field in the Slave API responses. This keeps the knowledge of what makes for a particular state transition in the Master while the GUI has enough data to indicate to the user `yes, you clicked configured_state = x, but we're still moving toward that state`<br/>
 Perhaps, a different name cfor the field could be helpful, e.g. `transitioning_to_configured_state` or preferrably something shorter.

**Comment by bwoebi** [comment]
@problame You are right in your understanding that it's just an indication. [currently]

> However, it will not violate or worsen availability constraints imposed by the administrator. ~ 7.2 Enum SlaveState

Though, I feel like if this is important to you, why don't you just put it into maintenance? If I want to disable it, I probably want to really disable it and mess with the files directly, shutdown or whatever. I do not want to have surprises because some mongod instance and my actions conflict.

Alternatively I'd suggest to have buttons to kill all mongods on a slave and eventually allow changes with a confirmation dialog if there are still mongods running.

**Comment by problame** [comment]
API changes implemented in 980b88d03d5f9ec97d6df9785a354d722c8fd623 and 80a0058a2fd657b247a1797d0d1d76f2bacace27

**Comment by problame** [comment]
GUI changes implemented in `eae0ca54d9808ccdb945fcca467e7a4c5a60cf77` and `28ba854a8fc25fb2323bd2e1690418c7a8016495` @janisstreib add slave-shows-mongod
