### ISSUE TITLE
Replica Set Elections: Volatile Slaves

### ISSUE THREAD

**Issue by problame** [KIT-MAMID/mamid#23]
Reading through https://docs.mongodb.com/manual/core/replica-set-elections/

- all writes to a replica set go to the current primary
- when a primary steps down, becomes unreachable or by some other means, an election takes place
- during the election, the remaining reachable members are read-only
- once a new primary is elected, the writes go to this new primary then

Of course, it depends on the application's specific

- read preference (default: read only from primary) https://docs.mongodb.com/manual/core/read-preference/
- write concern (default: ack from primary sufficent) https://docs.mongodb.com/manual/core/replica-set-write-concern/

(check the Databases lecture slides if you don't know what Mongod does there) 

However, the generic usecase targeting **minimized risk of data loss** (and the only one we have to support as best as possible according to the functional spec & design document), seems to be either of the following options:

1.  `one of many persistent=primary, volatiles=non-voting secondaries`
 * when all primaries is down, the election won't find a new primary and the replica set is read-only until a persistent host becomes available
 * => **minimal risk of data loss in case volatiles loose power**
2. `one of many persistent=primary, volatiles=voting secondaries with degraded priority`
 * when a volatile becomes primary and no persistent is available, the data written to DB is not safe yet
 * what happens when a persistent with higher priority comes back online? does another election take place automatically?

Given the default read preference / write concern **and** persistent hosts being the preferred primaries, this will most likely not yield the performance expected from in-memory hosts. 

I'm unsure what to do here, needs to be discussed rather sooner than later.

**Comment by bwoebi** [comment]
I think we really should just ask them what they prefer regarding requiring a persistent host or continuing with volatiles.

Do we actually set priorities for persistent hosts? I think it should be enough to have _any one_ persistent being primary.

**Comment by problame** [comment]
Result from team meeting:

- volatiles should be primaries
- persitents should still be allowed to vote, but with lower priority
- no mamid-controlled reelection in case a persistent becomes
