### ISSUE TITLE
slave/master: rs.remove() support when shutting down Mongod

### ISSUE THREAD

**Issue by problame** [KIT-MAMID/mamid#25]
https://docs.mongodb.com/manual/reference/method/rs.remove/#rs.remove

should be used, need to investigate whether `remove()` can be used from the slave that shall be removed.

alternatively, and maybe even better: infer the members to be `remove()`d from the `replica_set_members` field in the MSP `Mongod` object.

**Comment by bwoebi** [comment]
rs.remove() is a wrapper for mongo shell which does a replSetReconfig internally. There is nothing I can do on the slave side.

The `ReplicaSetMembers` just need to be updated and sent to the slave, which will then issue a proper replSetReconfig.

**Comment by problame** [comment]
Remains to be tested but should work.
