### ISSUE TITLE
Introduce shared key for internal authentication

### ISSUE THREAD

**Issue by janisstreib** [KIT-MAMID/mamid#31]
Implement a sherd key for internal authentication in rpelica sets.
We use the same key for the whole cluster.
See https://docs.mongodb.com/manual/core/security-internal-authentication/#keyfiles

- [x] Implement GUI representation of the shared key
- [x] Extend the DB to store the key
 - [ ] Generate a key if empty (?)
- [x] Extend the MasterAPI to be able to get/post a key string (system api e.g. `/api/system/key`)
 - Constraints:
   - between 6 and 1024 characters
    - whitespace is ignored
- [x] Extend the MSP to transport the keyFile content in each mongod object
- [x] Start mongods wit the `--keyFile` option
 - [x] Make shure that mongods are correctly stopped (with the old key) and lauch with the new key 
 - [x] Enshure, that the keyFile has correct permissions ~~~(`400`)~~~ (`600`)

**Comment by problame** [comment]
Fixed as of `71decc47a00ee2fa10668d4a4e2b9e5ba74a3b1e`
