### ISSUE TITLE
TLS for slave HTTP

### ISSUE THREAD

**Issue by janisstreib** [KIT-MAMID/mamid#32]
I prupose the follwing procedure:
- Each slave has its (not necessarily unique) cert and private key, signed by a _cluster local_ CA and supplied via the cmd.
- When the mater connects to the slave, it only allows connections with certs signed by the CA.
- The CA/PKI structure will not be managed by the master.

=> Therefore I prupose to place the CA cert into the master as reference to simplify the implementation.

- [x] Add cert/key parameters to the slave cmd
- [x] Serve http with TLS instead of plain HTTP on the slave
 - Only use _proper_ ciphers, please ;)
- [x] Use http with TLS + client cert instead of plain HTTP on the master
- [x] Configure the CA in the master
 - (Optional) Add CA to MaterAPI (`/api/system`)
 - (Optional) Add GUI setting or display for the CA
 - Alternatively: Add commandline parameter for the reference CA to master cmd
- [x] Implement connection check in the deployer/MSP and generate appropriate probelms
- [x] Implement client cert check in the slave
- [ ] Document procedure in the manual (see #33)

**Comment by problame** [comment]
remove hardcoded endpoints

**Comment by janisstreib** [comment]
Done with 44519b

**Comment by janisstreib** [comment]
Implemented cert auth in 837f43b
