### ISSUE TITLE
Slave: `replica set configuration version` errors when deploying a Mongod

### ISSUE THREAD

**Issue by problame** [KIT-MAMID/mamid#42]
When deploying a slave, the Slave returns the error

```
New replica set configuration version must be greater than old, but 87768 is not greater than 109003 for replica set r1
```

While the instances are still started and appear to be in the same replica set, we

- don't know whether the instance is actually configured properly (settings besides `--rs``)
- don't know what this error means.

@bwoebi please investigate.

I have to add that the slave on `master` still deadlocks when `EstablishMongodState()`, I use @antonxy 's changes in `origin/slave_fix_stopping` branch.

**Comment by antonxy** [comment]
Fixed in 2cd5bc43a2e9a933ae13b3e4e77c5c23b0098152
