### ISSUE TITLE
Monitor / ClusterAllocator: DesiredState.replicaSetMembers not set 

### ISSUE THREAD

**Issue by problame** [KIT-MAMID/mamid#48]
`DesiredState.replicaSetMembers not` not set.
=> always leads to a mismatch if >= 1 Mongod is observed.

However, the Deployer computes the desired members dynamically right now, hence deployment still works.

=> fix this after the recent `rs.initiate()` issues

**Comment by antonxy** [comment]
Fixed as of 3bda3a2fa76fdae1af6737d4538590f1b78e9fc1
