### ISSUE TITLE
Slave: check MongoDB version to be >= MongoDB 3.2 

### ISSUE THREAD

**Issue by problame** [KIT-MAMID/mamid#49]
Error handling has changed somewhere between `MongoDB 2.6` to `MongoDB 3.2`.

The slave in the `rsinitiate` branch uses MongoDB error codes, which are available in MongoDB 3.2 but not in 2.6.

Command in Mongo Shell to determine the version of the database: `db.version()`.

Use semantic versioning to allow all versions greater than or equal 3.2

If motivated, find which version of MongoDB introduced the erorr codes required in commit `fillhere`

**Comment by janisstreib** [comment]
Fixed with  	d5e2b5b
